
GET http://localhost:5000/userInf
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYW5obG9uZ2RlcHRyYWkyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoibG9uZ2RlcHRyYWkiLCJpYXQiOjE3MTMwMjc1NzcsImV4cCI6MTcxMzAzMTE3N30.ddqag9hBzjZVrXiQTI4e094D_FwYtClDWqOYunb5-9w

###
PUT http://localhost:5000/userInf/update
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYW5obG9uZzE3MTAwMkBnbWFpbC5jb20iLCJwYXNzd29yZCI6ImxvbmdkZXB0cmFpIiwiaWF0IjoxNzEyODY4MjgyLCJleHAiOjE3MTI4NjgzMTJ9.qwnPdIXjryEvxXjJwQ_I6NfgAE4fsql4kbgecj0FHZw

{
  "update": {
    "phone": 374446661543,
    "address": "HN"
  }
}
####
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "chanhlongdeptrai2@gmail.com",
  "password": "longdeptrai",
  "nameaccount": "long17",
  "phone": 333456789,
  "address": "TpHCM",
  "email": "long.nguyen2002043@std.ttu.edu.vn"
}

###
POST http://localhost:5500/login
Content-Type: application/json

{
  "username": "chanhlongdeptrai2@gmail.com",
  "password": "longdeptrai"
}